# Generated by Django 3.2.15 on 2022-08-11 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(db_column='created_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_create_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'e_categories',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
